### ISSUE TITLE
Add unit test pipeline

### ISSUE THREAD

**Issue by kair8m** [nvimdev/lspsaga.nvim#1005]
It would be nice to add unit test pipeline to avoid potential trivial mistakes (typo's for instance). Each feature should be merged to `main` branch after CI verification. Thus, it will prevent anyone from breaking the plugin.

**Comment by glepnir** [comment]
why i don't add test. for some functional test can be add. but there has lots of ui relate things. write test for these a little trouble.

**Comment by scottming** [comment]
Do you think it's possible to separate the UI presentation and data calculation logic as much as possible? Because this would be very helpful for testing.

Also, I am a functional programming enthusiast and also deeply interested in unit testing. I found two techniques that are very helpful for testing and code maintenance:

1. In functional programming languages, we always like to push mutation to the edge to directly test the middle part. This is similar to what people often call Dependency Rejection, which is the simplest way to make code easier to test. Scott Wlaschin has an excellent example here: https://fsharpforfunandprofit.com/posts/dependencies/#approach-2-dependency-rejection . The concept discussed in "Functional Core, Imperative Shell" (https://www.destroyallsoftware.com/screencasts/catalog/functional-core-imperative-shell) is also similar. Additionally, I have used this approach in neotest-elixir.

2. Humble Object pattern - this pattern was originally invented to solve the problem of difficult-to-test UIs. Our code can be divided into two parts: deep (heavy business logic but few dependencies) or wide (many dependencies but little decision-making logic). If a module is both deep and wide, then it becomes difficult to test and maintain. I have used this pattern extensively at work because it really solves many problems.

I am happy to work with you to solve these testing issues if needed, but I would first like to know your thoughts and plans. @glepnir

**Comment by glepnir** [comment]
there is no fp style currently. this plugin  has lots of too old code and some bad design. currently I am developing the next version. refactor some module. abstract some public interfaces. then i can try to add a bit unit test.  but just a little test case. if you want help  PR welcome when 0.3 publish :)
