### ISSUE TITLE
[0.3.0]  file path back to finder title 

### ISSUE THREAD

**Issue by alextrastero** [nvimdev/lspsaga.nvim#1076]
When searching for references of a method, I use `lsp_finder` however from the generated list I cannot see what file is on the preview panel on the right

This is how Telescope shows the preview panel
![image](https://github.com/nvimdev/lspsaga.nvim/assets/4152819/ca9e165f-70f1-475f-9724-c1dd3e518507)

This is how lspsaga renders the panel
![image](https://github.com/nvimdev/lspsaga.nvim/assets/4152819/2a680146-c55b-428e-9812-19d763e870e7)

**Comment by alextrastero** [comment]
It would be great if I could have like Telescope the filepath on top of the preview panel or maybe a clearer sidebar... thoughts?

**Comment by glepnir** [comment]
the current filename will highlight  `MetricsDropDown` . before finder have fname in title. but i think it not make sense ?

**Comment by alextrastero** [comment]
Sorry, I didn't mean the filename but rather the filepath, I want to know if the file I'm seeing in the preview is a:
`/lib1/components/MetricDropdown.tsx` or /lib2/components/MetricDropdown.tsx`

**Comment by glepnir** [comment]
The reason for removing the title is. Because some file paths are too long. When the window width is smaller than the path. Truncating and leaving intact does not satisfy some people's needs. Some people need the right part and some people need the left part. I am going to add some implementation of title length truncation in neovim core. It is similar to stl truncation. However, for the current refactoring of the next version, I will use Layout to support more layouts. Add the title back and respect the ui.title option.

**Comment by alextrastero** [comment]
🙏🏼 just as an FYI for the future, Telescope has the following:
```
    -- path_display = { "smart" },
    path_display = { "truncate" },
```

**Comment by glepnir** [comment]
hmm nope . telescope use it own title implemetion. the neovim float window title write by me not same as telescope way.  so it may work like statusline use `<` to truncate. just a draft .
