### ISSUE TITLE
lsp finder error

### ISSUE THREAD

**Issue by obmutescences** [nvimdev/lspsaga.nvim#1121]
### Describe the bug

lspsaga lsp_finder not working.
![Snipaste_2023-07-10_10-55-48](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/444f9073-f427-4350-80b5-a334ccaf279f)

### Steps to reproduce

run in any func

### Expected behavior

finder

### Neovim version (nvim -v)

0.10.0

### lspsaga commit

main branch 

### Terminal name/version

kitty

**Comment by CnsMaple** [comment]
you can try :
`vim.keymap.set("n", "gh", "<cmd>Lspsaga lsp_finder<CR>")`->`vim.keymap.set("n", "gh", "<cmd>Lspsaga finder<CR>")`
the `lsp_finder` to the `finder`

**Comment by obmutescences** [comment]
some error like this.
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/73ab1fb5-5984-4db0-b38e-3a41084f772e)

**Comment by obmutescences** [comment]
> some error like this. ![image](https://user-images.githubusercontent.com/29330637/252202193-73ab1fb5-5984-4db0-b38e-3a41084f772e.png)

changed to lspsaga finder

**Comment by glepnir** [comment]
Provide reproducr step lsp_finder chang to finder

**Comment by obmutescences** [comment]
> Provide reproducr step lsp_finder chang to finder

corner error. 
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/030b685b-04d9-4677-b315-10915ac35bf4)
still some error
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/15a73bd7-26bc-4443-be59-c3dd4bd44a7d)

**Comment by obmutescences** [comment]
my neovim version:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/d3001576-ad01-4bc3-851a-81ce4bb5f51e)

**Comment by obmutescences** [comment]
直接在那个 read_redis_keys_with_prefix 上执行  gr
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/49e447f2-d297-42ef-ba80-d5e4a070726a)

**Comment by obmutescences** [comment]
按下 Esc 就变成了这样
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/d67fbeb7-aa41-4db8-a1ba-d35c3aa79e50)

**Comment by glepnir** [comment]
我不太能重现你这个

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/ef825b0d-a279-4c26-9933-d9de9566baf5)

**Comment by bryanmaina** [comment]
I have the same issues after updating. I replace `lsp_finder` by `finder`. I have only tested it on with nextjs code and these are the problems that I notice with `finder` compared to `lsp_finder`.

It will find everything about the standard libs.
![image](https://github.com/nvimdev/lspsaga.nvim/assets/8012851/31b2fb9b-3122-4b69-854b-ecca183804cc)
![image](https://github.com/nvimdev/lspsaga.nvim/assets/8012851/855c722f-9a38-45e3-ae3a-962277a51830)

but it does not find everything about things you have wrote self and used in another file. In this example it should have found an implementation in another file. You can not open your own implementations without this functionality.
![image](https://github.com/nvimdev/lspsaga.nvim/assets/8012851/957e8705-f029-4bb7-a2e9-8743417f1300)

But, It does find things that are defined in the same file. Although, I feel like variable definitions in the same file normally 
 appear under definition rather than implementation(I might be wrong).
![image](https://github.com/nvimdev/lspsaga.nvim/assets/8012851/93507ed8-9f57-4c59-98ea-a962096f9c1c)

I have never used `finder` before I can not say if it does have the same capabilities as `lsp_find`.

**Comment by glepnir** [comment]
> but it does not find everything about things you have wrote self and used in another file. In this example it should have found an implementation in another file. You can not open your own implementations without this functionality.

this might not finder error ? move cursor to interface type. then do finder if finder not show any implement result try `:lua vim.lsp.buf.implementation()` and see what happen if this can return a result but finder show nothing then it could be finder bug .I need some nextjs code to reproduce .

**Comment by glepnir** [comment]
我用了head 和 0.9.1 都没重现。

**Comment by obmutescences** [comment]
我竖屏 横屏都不行，配置只设置了
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/5794cfb7-6e35-4049-bae7-9bea9d3cfa8d)
max_height = 0.5
你说的窗口大小我怎么看

**Comment by glepnir** [comment]
更新到最新的commit  最小配置 . `nvim --clean - u min.lua`

```lua
vim.opt.rtp:append('~/workspace/lspsaga.nvim')
vim.opt.rtp:append('~/workspace/nvim-lspconfig')
local lspconfig = require('lspconfig')
lspconfig.lua_ls.setup({})
require('lspsaga').setup({})

```

**Comment by obmutescences** [comment]
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/f6570361-08db-450d-a9a2-00f62bb14478)
这是没有 lsp 服务器的原因吗，啥也没安装，按照你上面这样启动的

**Comment by glepnir** [comment]
默认的finder 是引用和实现。 `Lspsaga finder def` 在finder显示定义。 看文档https://dev.neovim.pro/

**Comment by obmutescences** [comment]
是带上函数名的意思吗 
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/af656f14-d0a8-42cb-980c-b22d9a3f8f25)

**Comment by glepnir** [comment]
函数哪里来的实现？ `implementation` 只针对interface type 。我说了使用最小配置 测试。

**Comment by glepnir** [comment]
okay , `typescript-language-server` can't handle this like you want.  maybe need report to `typescript-language-server`?

**Comment by obmutescences** [comment]
> 函数哪里来的实现？ `implementation` 只针对interface type 。我说了使用最小配置 测试。

我现在把配置设置成如下配置
![image](https://github.com/nvimdev/lspsaga.nvim/assets/29330637/e9585066-13ea-45aa-84c2-b87fd3e25146)
这样就没有问题了，但是我只要改 ui 里的 border 为 solid, shadow 或者 none 就出现上面那个错误

**Comment by glepnir** [comment]
fixed. finder 可以组合各种lsp method 其他的你可以注册 在命令行传递或者default

**Comment by obmutescences** [comment]
> fixed. finder 可以组合各种lsp method 其他的你可以注册 在命令行传递或者default

好的，大佬辛苦了
